os: linux
dist: trusty
language: c
compiler: gcc

script:
  - cmake -DBUILD_ALL=ON -DCMAKE_BUILD_TYPE:String="Coverage" ./
  - make
  - ctest -T Test --timeout 600 -VV
  - ctest -T MemCheck --timeout 600
  - cat Testing/Temporary/MemoryChecker.*.log || exit 0
  - ctest -T Coverage -VV

addons:
  apt:
    packages:
    - valgrind

